# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jk/Documents/FPGA/EDA_Class/DDS_Vivado/vivado/DDS.srcs/sources_1/ip/rom/rom.xci
# IP: The module: 'rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jk/Documents/FPGA/EDA_Class/DDS_Vivado/vivado/DDS.gen/sources_1/ip/rom/rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/jk/Documents/FPGA/EDA_Class/DDS_Vivado/vivado/DDS.srcs/sources_1/ip/rom/rom.xci
# IP: The module: 'rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jk/Documents/FPGA/EDA_Class/DDS_Vivado/vivado/DDS.gen/sources_1/ip/rom/rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
